\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{cv}

\LoadClass{Awesome-CV/awesome-cv}

%
% Modifications
%

% change default color
% Color for highlights
% Awesome Colors: awesome-emerald, awesome-skyblue, awesome-red, awesome-pink, awesome-orange
%                 awesome-nephritis, awesome-concrete, awesome-darknight
\colorlet{awesome}{awesome-darknight}

% enable section color
\setbool{acvSectionColorHighlight}{true}
